<a href="https://colab.research.google.com/github/sajalgoyal007/AIML-Training-Projects/blob/main/Practice/Pandas_You.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Pandas Series**
A series is a one dimensional lebelled array capable of holding any data type.The axis labels are collectively called index

**Creating Series**

In [74]:
import numpy as np
import pandas as pd

In [75]:
labels = ['a', 'b', 'c']
mylists = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1: 10, 2: 20, 3: 30}

In [76]:
pd.Series(mylists)

0    10
1    20
2    30
dtype: int64

In [77]:
pd.Series(mylists, index = labels)

a    10
b    20
c    30
dtype: int64

In [78]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [79]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [80]:
d = {'a': 10, 'b': 20, 'c': 30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

**Creating DataFrame**

In [81]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 24, 35, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [82]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   24     Paris   70000
2  Peter   35    Berlin   62000
3  Linda   32    London   85000

In [83]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)

In [84]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting and Indexing of Columns**

In [85]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [86]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [87]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [88]:
df2['Designation'] = ['Doctor', 'Engineer', 'Doctor', 'Engineer']

In [89]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

Remove a column

In [90]:
df2.drop('Designation', axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [91]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [92]:
df2.drop('Designation', axis = 1, inplace = True)

In [93]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [94]:
df2.drop(['City', 'Salary'], axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

Selecting the Row

In [95]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [96]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [97]:
df2.loc[[0, 1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [98]:
df.iloc[3]  # same as loc

Name       Linda
Age           32
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subset of rows and columns

In [99]:
df.loc[[1, 2]][['City', 'Salary']]

     City  Salary
1   Paris   70000
2  Berlin   62000

Conditional Selection

In [100]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [101]:
# i only want to see those people whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [102]:
# i only want those people whose age is above 30 and City must be paris
df2[(df2['Age']>30) &  (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

**Missing Data**

Finding Missing Data

In [103]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [104]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [105]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [106]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [107]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [108]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

**Removing Missing Data**  --> Work on the basis of rows

In [109]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [110]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [111]:
df.dropna(thresh=3)  # At least 3 not null value honi chahiye

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

**Filling the missing data**

In [112]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [113]:
values = {'A':0, 'B':100, 'C':300, 'D':400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [114]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [115]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

**MergingJoiningConcatination**

Merging 2 dataframes

In [116]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'HR', 'IT']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [117]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  peter    Finance
3            4  Linda         HR
4            5    Bob         IT

In [118]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [119]:
pd.merge(employees, salaries, on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  peter    Finance   65000   7000

In [120]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  peter    Finance   65000   7000

In [121]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  peter    Finance  65000.0   7000.0
3            4  Linda         HR      NaN      NaN
4            5    Bob         IT      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [122]:
pd.merge(employees, salaries, on='employee_id', how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  peter    Finance  65000.0   7000.0
3            4  Linda         HR      NaN      NaN
4            5    Bob         IT      NaN      NaN

In [123]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatination of DataFrames

In [124]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2'],
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5'],
})

In [125]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [126]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [127]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [128]:
pd.concat([df2, df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [129]:
pd.concat([df1, df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining two dataframes

In [130]:
df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'Score': [85, 90, 75]
}, index=[2, 3, 4])

In [131]:
df1

      Name
1    Alice
2      Bob
3  Charlie

In [132]:
df2

   Score
2     85
3     90
4     75

In [133]:
df1.join(df2)

      Name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [134]:
df1.join(df2, how='outer')

      Name  Score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [135]:
df2.join(df1)

   Score     Name
2     85      Bob
3     90  Charlie
4     75      NaN

**GroupByAggregation**

Group by

In [136]:
data = {
    'category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quanity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [137]:
df

  category Store  Sales  Quanity       Date
0        A    S1    100       10 2023-01-01
1        B    S1    200       15 2023-01-02
2        A    S2    150       12 2023-01-03
3        B    S2    250       18 2023-01-04
4        A    S1    120        8 2023-01-05
5        B    S2    180       20 2023-01-06
6        A    S2    200       15 2023-01-07
7        B    S1    300       25 2023-01-08

In [138]:
#Group by category and calculate the sum of sales
cat = df.groupby('category')['Sales'].sum()
cat

category
A    570
B    930
Name: Sales, dtype: int64

In [139]:
#Group by store and calculate the sum of sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [140]:
#groupby multiple column
#groupby category and store
cat = df.groupby(['category', 'Store'])['Sales'].sum()
cat

category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [144]:
df['Sales'].mean()
#mean, median, min max, count, std

np.float64(187.5)

In [146]:
df['Sales'].agg(['sum', 'mean', 'count', 'std', 'median', 'min', 'max'])

sum       1500.000000
mean       187.500000
count        8.000000
std         66.062741
median     190.000000
min        100.000000
max        300.000000
Name: Sales, dtype: float64

**Pivot Tables**

In [147]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    973     72   John  January      Q1
1  2023-01-02       B   West    318     94   Mary  January      Q1
2  2023-01-03       C  North    462     56    Bob  January      Q1
3  2023-01-04       D  South    283     67  Alice  January      Q1
4  2023-01-05       A   East    824     36   John  January      Q1
5  2023-01-06       B   West    650     56   Mary  January      Q1
6  2023-01-07       C  North    710     74    Bob  January      Q1
7  2023-01-08       D  South    445     98  Alice  January      Q1
8  2023-01-09       A   East    856     41   John  January      Q1
9  2023-01-10       B   West    479     70   Mary  January      Q1
10 2023-01-11       C  North    531     74    Bob  January      Q1
11 2023-01-12       D  South    415     97  Alice  January      Q1
12 2023-01-13       A   East    111     72   John  January      Q1
13 2023-01-14       B   West    193     88   Mary  January      Q1
14 2023-01-15       C  North    179     85    Bob  January      Q1
15 2023-01-16       D  South    713     25  Alice  January      Q1
16 2023-01-17       A   East    409     42   John  January      Q1
17 2023-01-18       B   West    408     65   Mary  January      Q1
18 2023-01-19       C  North    263     47    Bob  January      Q1
19 2023-01-20       D  South    661     27  Alice  January      Q1

In [149]:
pd.pivot_table(df, values='Sales', index = 'Region', columns = 'Product')

Product      A      B      C      D
Region
East     634.6    NaN    NaN    NaN
North      NaN    NaN  429.0    NaN
South      NaN    NaN    NaN  503.4
West       NaN  409.6    NaN    NaN

In [150]:
pd.pivot_table(df, values='Sales', index = 'Region', columns = 'Product', aggfunc='median')

Product      A      B      C      D
Region
East     824.0    NaN    NaN    NaN
North      NaN    NaN  462.0    NaN
South      NaN    NaN    NaN  445.0
West       NaN  408.0    NaN    NaN

In [153]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     634.6    NaN    NaN    NaN  52.6   NaN   NaN   NaN
North      NaN    NaN  429.0    NaN   NaN   NaN  67.2   NaN
South      NaN    NaN    NaN  503.4   NaN   NaN   NaN  62.8
West       NaN  409.6    NaN    NaN   NaN  74.6   NaN   NaN

**Cross Tabs**

In [154]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**Operations**      
**DataFrame basic operations**

In [186]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [187]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [188]:
df1.shape

(5, 3)

In [189]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [190]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [191]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [192]:
df1['A'] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**DataFrames** Appling Functions

In [193]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [194]:
def square(x):
  return x**2

In [195]:
df1['B'] = df1['B'].apply(square)

In [196]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [197]:
df1['D'] = df1['A'].apply(square)

In [198]:
df1

   A     B    C   D
0  1   100  100   1
1  2   400  200   4
2  3   900  300   9
3  4  1600  400  16
4  5  2500  500  25

In [199]:
df1['E'] = df1['B'].apply(lambda x: x**2)

In [200]:
df1

   A     B    C   D        E
0  1   100  100   1    10000
1  2   400  200   4   160000
2  3   900  300   9   810000
3  4  1600  400  16  2560000
4  5  2500  500  25  6250000